name: Build and Create Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create build directory
      run: |
          mkdir -p build
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Download external library
      run: |
          wget https://github.com/xxxajk/spi4teensy3/archive/master.zip -O /tmp/spi4teensy3.zip
          unzip /tmp/spi4teensy3.zip -d /tmp
    - name: Build firmware and SPIFFS
      run: |
        platformio run --target buildfs
        platformio run 
        #--target build
    
    - name: Upload firmware.bin
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: .pio/build/esp32dev/firmware.bin
    - name: Upload spiffs.bin
      uses: actions/upload-artifact@v2
      with:
        name: spiffs
        path: .pio/build/esp32dev/spiffs.bin
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASETOKEN }}
        with:
          tag_name: v1.0.0  # Replace with your desired tag name
          release_name: Release v1.0.0  # Replace with your desired release name
          body: |
             This is the first release of my project.
          draft: false
          prerelease: false
          token: ${{ env.GITHUB_TOKEN  }}


      - name: Upload Firmware
        id: upload_firmware
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/esp32dev/firmware.bin
          asset_name: firmware.bin
          asset_content_type: application/octet-stream
          token: ${{ secrets.RELEASETOKEN }}

      - name: Upload SPIFFS
        id: upload_spiffs
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/esp32dev/spiffs.bin
          asset_name: spiffs.bin
          asset_content_type: application/octet-stream
          token: ${{ secrets.RELEASETOKEN }}

