name: Build and Create Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Download external library
      run: |
          wget https://github.com/xxxajk/spi4teensy3/archive/master.zip -O /tmp/spi4teensy3.zip
          unzip /tmp/spi4teensy3.zip -d /tmp
    - name: Build firmware and SPIFFS
      run: |
        platformio run --target buildfs
        platformio run --target build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          This is an automated release generated by GitHub Actions.
        draft: false
        prerelease: false
    - name: Upload firmware.bin
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: .pio/build/esp32/firmware.bin
    - name: Upload spiffs.bin
      uses: actions/upload-artifact@v2
      with:
        name: spiffs
        path: .pio/build/esp32/spiffs.bin
